# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: '3.4'

services:
  destination-data-server:
    container_name: destination-data-server
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "${SERVER_PORT}:${REF_SERVER_PORT}"
