# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:  
  db:
    container_name: pgdb
    hostname: pgdb
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_EXT_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: -p "${DB_PORT}"