services:  
  db:
    container_name: pgdb
    hostname: pgdb
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: test_db
    ports:
      - "5432:${DB_EXT_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data