version: '3.4'

services:
  destination-data-server:
    container_name: destination-data-server
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "${SERVER_PORT}:${REF_SERVER_PORT}"
