# This file configures the destination-data-server routing the application's port to the one that should be exposed by the server
version: "2"
services:
  destination-data-server:
    container_name: destination-data-server
    env_file: .env
    build: .
    restart: always
    ports:
      - "${REF_SERVER_PORT}:${REF_SERVER_EXPOSED_PORT}"
