module.exports = {
  defaults: {
    eventStatus: {
      canceled: "canceled",
      published: "published",
    },
    resourceTypes: {
      agents: "agents",
      categories: "categories",
      events: "events",
      eventSeries: "eventSeries",
      features: "features",
      lifts: "lifts",
      mediaObjects: "mediaObjects",
      mountainAreas: "mountainAreas",
      skiSlopes: "skiSlopes",
      snowparks: "snowparks",
      venues: "venues",
    },
    seriesFrequencies: {
      daily: "daily",
      weekly: "weekly",
      monthly: "monthly",
      bimonthly: "bimonthly",
      quarterly: "quarterly",
      annual: "annual",
      biennial: "biennial",
      triennial: "triennial",
    },
  },
  schemas: {
    abstracts: {
      _name: "abstracts",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    addresses: {
      _name: "addresses",
      id: "id",
      country: "country",
      zipcode: "zipcode",
      type: "type",
    },
    agents: {
      _name: "agents",
      id: "id",
    },
    categories: {
      _name: "categories",
      id: "id",
      resourceId: "resource_id",
      namespace: "namespace",
    },
    categoryCoveredTypes: {
      _name: "category_covered_types",
      categoryId: "category_id",
      type: "type",
    },
    categorySpecializations: {
      _name: "category_specializations",
      parentId: "parent_id",
      childId: "child_id",
    },
    cities: {
      _name: "cities",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    complements: {
      _name: "complements",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    contactPoints: {
      _name: "contact_points",
      id: "id",
      agentId: "agent_id",
      addressId: "address_id",
      email: "email",
      telephone: "telephone",
      availableHours: "available_hours",
    },
    contributors: {
      _name: "contributors",
      contributorId: "contributor_id",
      eventId: "event_id",
    },
    descriptions: {
      _name: "descriptions",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    events: {
      _name: "events",
      id: "id",
      capacity: "capacity",
      endDate: "end_date",
      parentId: "parent_id",
      publisherId: "publisher_id",
      seriesId: "series_id",
      startDate: "start_date",
      status: "status",
    },
    eventSeries: {
      _name: "event_series",
      id: "id",
      frequency: "frequency",
    },
    eventStatus: {
      _name: "event_status",
      status: "status",
      title: "title",
    },
    featureCoveredTypes: {
      _name: "feature_covered_types",
      featureId: "feature_id",
      type: "type",
    },
    features: {
      _name: "features",
      id: "id",
      resourceId: "resource_id",
      namespace: "namespace",
    },
    featureSpecializations: {
      _name: "feature_specializations",
      parentId: "parent_id",
      childId: "child_id",
    },
    languageCodes: {
      _name: "language_codes",
      lang: "lang",
      title: "title",
    },
    mediaObjects: {
      _name: "media_objects",
      id: "id",
      contentType: "content_type",
      duration: "duration",
      height: "height",
      license: "license",
      width: "width",
      copyrightOwnerId: "copyright_owner_id",
    },
    multimediaDescriptions: {
      _name: "multimedia_descriptions",
      resourceId: "resource_id",
      mediaObjectId: "media_object_id",
    },
    names: {
      _name: "names",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    organizers: {
      _name: "organizers",
      organizerId: "organizer_id",
      eventId: "event_id",
    },
    regions: {
      _name: "regions",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    resourceCategories: {
      _name: "resource_categories",
      categorizedResourceId: "categorized_resource_id",
      categoryId: "category_id",
    },
    resources: {
      _name: "resources",
      id: "id",
      type: "type",
      odhId: "odh_id",
      dataProvider: "data_provider",
      createdAt: "created_at",
      lastUpdate: "last_update",
      simpleUrl: "simple_url",
    },
    resourceTypes: {
      _name: "resource_types",
      type: "type",
      title: "title",
    },
    seriesFrequencies: {
      _name: "series_frequencies",
      frequency: "frequency",
      title: "title",
    },
    shortNames: {
      _name: "short_names",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    sponsors: {
      _name: "sponsors",
      sponsorId: "sponsor_id",
      eventId: "event_id",
    },
    streets: {
      _name: "streets",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    urls: {
      _name: "urls",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
  },
  views: {
    abstractObjects: {
      _name: "abstract_objects",
      id: "id",
      abstract: "abstract",
    },
    descriptionObjects: {
      _name: "description_objects",
      id: "id",
      description: "description",
    },
    nameObjects: {
      _name: "name_objects",
      id: "id",
      name: "name",
    },
    shortNameObjects: {
      _name: "short_name_objects",
      id: "id",
      short_name: "short_name",
    },
    urlObjects: {
      _name: "url_objects",
      id: "id",
      url: "url",
    },
    categoriesArrays: {
      _name: "categories_arrays",
      id: "id",
      categories: "categories",
    },
    multimediaDescriptionsArrays: {
      _name: "multimedia_descriptions_arrays",
      id: "id",
      multimediaDescriptions: "multimedia_descriptions",
    },
    cityObjects: {
      _name: "city_objects",
      id: "id",
      city: "city",
    },
    complementObjects: {
      _name: "complement_objects",
      id: "id",
      complement: "complement",
    },
    regionObjects: {
      _name: "region_objects",
      id: "id",
      region: "region",
    },
    streetObjects: {
      _name: "street_objects",
      id: "id",
      street: "street",
    },
    addressObjects: {
      _name: "address_objects",
      id: "id",
      address: "address",
    },
    resourceObjects: {
      _name: "resource_objects",
      id: "id",
      resource: "resource",
    },
  },
};
