module.exports = {
  defaults: {
    eventStatus: {
      canceled: "canceled",
      published: "published",
    },
    resourceTypes: {
      agents: "agents",
      categories: "categories",
      events: "events",
      eventSeries: "eventSeries",
      features: "features",
      lifts: "lifts",
      mediaObjects: "mediaObjects",
      mountainAreas: "mountainAreas",
      skiSlopes: "skiSlopes",
      snowparks: "snowparks",
      venues: "venues",
    },
    seriesFrequencies: {
      daily: "daily",
      weekly: "weekly",
      monthly: "monthly",
      bimonthly: "bimonthly",
      quarterly: "quarterly",
      annual: "annual",
      biennial: "biennial",
      triennial: "triennial",
    },
  },
  schemas: {
    abstracts: {
      _name: "abstracts",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    addresses: {
      _name: "addresses",
      id: "id",
      country: "country",
      zipcode: "zipcode",
      type: "type",
    },
    agents: {
      _name: "agents",
      id: "id",
    },
    areaLifts: {
      _name: "area_lifts",
      areaId: "area_id",
      liftId: "lift_id",
    },
    areaSkiSlopes: {
      _name: "area_ski_slopes",
      areaId: "area_id",
      skiSlopeId: "ski_slope_id",
    },
    areaSnowparks: {
      _name: "area_snowparks",
      areaId: "area_id",
      snowparkId: "snowpark_id",
    },
    categories: {
      _name: "categories",
      id: "id",
      resourceId: "resource_id",
      namespace: "namespace",
    },
    categoryCoveredTypes: {
      _name: "category_covered_types",
      categoryId: "category_id",
      type: "type",
    },
    categorySpecializations: {
      _name: "category_specializations",
      parentId: "parent_id",
      childId: "child_id",
    },
    cities: {
      _name: "cities",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    complements: {
      _name: "complements",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    connections: {
      _name: "connections",
      aId: "a_id",
      bId: "b_id",
    },
    contactPoints: {
      _name: "contact_points",
      id: "id",
      agentId: "agent_id",
      addressId: "address_id",
      email: "email",
      telephone: "telephone",
      availableHours: "available_hours",
    },
    contributors: {
      _name: "contributors",
      contributorId: "contributor_id",
      eventId: "event_id",
    },
    descriptions: {
      _name: "descriptions",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    events: {
      _name: "events",
      id: "id",
      capacity: "capacity",
      endDate: "end_date",
      parentId: "parent_id",
      publisherId: "publisher_id",
      seriesId: "series_id",
      startDate: "start_date",
      status: "status",
    },
    eventSeries: {
      _name: "event_series",
      id: "id",
      frequency: "frequency",
    },
    eventStatus: {
      _name: "event_status",
      status: "status",
      title: "title",
    },
    eventVenues: {
      _name: "event_venues",
      venueId: "venue_id",
      eventId: "event_id",
    },
    featureCoveredTypes: {
      _name: "feature_covered_types",
      featureId: "feature_id",
      type: "type",
    },
    features: {
      _name: "features",
      id: "id",
      resourceId: "resource_id",
      namespace: "namespace",
    },
    featureSpecializations: {
      _name: "feature_specializations",
      parentId: "parent_id",
      childId: "child_id",
    },
    howToArrive: {
      _name: "how_to_arrive",
      placeId: "place_id",
      lang: "lang",
      content: "content",
    },
    languageCodes: {
      _name: "language_codes",
      lang: "lang",
      title: "title",
    },
    lifts: {
      _name: "lifts",
      id: "id",
      capacity: "capacity",
      personsPerChair: "persons_per_chair",
    },
    mediaObjects: {
      _name: "media_objects",
      id: "id",
      contentType: "content_type",
      duration: "duration",
      height: "height",
      license: "license",
      width: "width",
      copyrightOwnerId: "copyright_owner_id",
    },
    mountainAreas: {
      _name: "mountain_areas",
      id: "id",
      area: "area",
      totalParkLength: "total_park_length",
      totalSlopeLength: "total_slope_length",
    },
    multimediaDescriptions: {
      _name: "multimedia_descriptions",
      resourceId: "resource_id",
      mediaObjectId: "media_object_id",
    },
    names: {
      _name: "names",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    organizers: {
      _name: "organizers",
      organizerId: "organizer_id",
      eventId: "event_id",
    },
    places: {
      _name: "places",
      id: "id",
      addressId: "address_id",
      geometries: "geometries",
      length: "length",
      maxAltitude: "max_altitude",
      minAltitude: "min_altitude",
      openingHours: "opening_hours",
    },
    regions: {
      _name: "regions",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    resourceCategories: {
      _name: "resource_categories",
      resourceId: "resource_id",
      categoryId: "category_id",
    },
    resourceFeatures: {
      _name: "resource_features",
      resourceId: "resource_id",
      featureId: "feature_id",
    },
    resources: {
      _name: "resources",
      id: "id",
      type: "type",
      odhId: "odh_id",
      dataProvider: "data_provider",
      createdAt: "created_at",
      lastUpdate: "last_update",
      simpleUrl: "simple_url",
    },
    resourceTypes: {
      _name: "resource_types",
      type: "type",
      title: "title",
    },
    seriesFrequencies: {
      _name: "series_frequencies",
      frequency: "frequency",
      title: "title",
    },
    shortNames: {
      _name: "short_names",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
    skiSlopes: {
      _name: "ski_slopes",
      id: "id",
      difficultyEu: "difficulty_eu",
      difficultyUs: "difficulty_us",
    },
    snowConditions: {
      _name: "snow_conditions",
      id: "id",
      baseSnow: "base_snow",
      baseSnowRangeLower: "base_snow_range_lower",
      baseSnowRangeUpper: "base_snow_range_upper",
      groomed: "groomed",
      latestStorm: "latest_storm",
      obtainedIn: "obtained_in",
      primarySurface: "primary_surface",
      secondarySurface: "secondary_surface",
      snowMaking: "snow_making",
      snowOverNight: "snow_over_night",
    },
    snowparks: {
      _name: "snowparks",
      id: "id",
      difficulty: "difficulty",
    },
    sponsors: {
      _name: "sponsors",
      sponsorId: "sponsor_id",
      eventId: "event_id",
    },
    streets: {
      _name: "streets",
      addressId: "address_id",
      lang: "lang",
      content: "content",
    },
    subAreas: {
      _name: "sub_areas",
      childId: "child_id",
      parentId: "parent_id",
    },
    venues: {
      _name: "venues",
      id: "id",
    },
    urls: {
      _name: "urls",
      resourceId: "resource_id",
      lang: "lang",
      content: "content",
    },
  },
  views: {
    abstractObjects: {
      _name: "abstract_objects",
      id: "id",
      abstract: "abstract",
    },
    descriptionObjects: {
      _name: "description_objects",
      id: "id",
      description: "description",
    },
    nameObjects: {
      _name: "name_objects",
      id: "id",
      name: "name",
    },
    shortNameObjects: {
      _name: "short_name_objects",
      id: "id",
      short_name: "short_name",
    },
    urlObjects: {
      _name: "url_objects",
      id: "id",
      url: "url",
    },
    categoriesArrays: {
      _name: "categories_arrays",
      id: "id",
      categories: "categories",
    },
    multimediaDescriptionsArrays: {
      _name: "multimedia_descriptions_arrays",
      id: "id",
      multimediaDescriptions: "multimedia_descriptions",
    },
    cityObjects: {
      _name: "city_objects",
      id: "id",
      city: "city",
    },
    complementObjects: {
      _name: "complement_objects",
      id: "id",
      complement: "complement",
    },
    regionObjects: {
      _name: "region_objects",
      id: "id",
      region: "region",
    },
    streetObjects: {
      _name: "street_objects",
      id: "id",
      street: "street",
    },
    addressObjects: {
      _name: "address_objects",
      id: "id",
      address: "address",
    },
    resourceObjects: {
      _name: "resource_objects",
      id: "id",
      type: "type",
      dataProvider: "data_provider",
      lastUpdate: "last_update",
      abstract: "abstract",
      description: "description",
      name: "name",
      shortName: "short_name",
      url: "url",
      categories: "categories",
      media: "media",
    },
    howToArriveObjects: {
      _name: "how_to_arrive_objects",
      id: "id",
      howToArrive: "how_to_arrive",
    },
    areaLiftsArrays: {
      _name: "area_lifts_arrays",
      id: "id",
      areaLifts: "area_lifts",
    },
    areaSkiSlopesArrays: {
      _name: "area_ski_slopes_arrays",
      id: "id",
      areaSkiSlopes: "area_ski_slopes",
    },
    areaSnowparksArrays: {
      _name: "area_snowparks_arrays",
      id: "id",
      areaSnowparks: "area_snowparks",
    },
    subAreasArrays: {
      _name: "sub_areas_arrays",
      id: "id",
      subAreas: "sub_areas",
    },
    connectionsArrays: {
      _name: "connections_arrays",
      id: "id",
      connections: "connections",
    },
    snowConditionObjects: {
      _name: "snow_condition_objects",
      id: "id",
      snowCondition: "snow_condition",
    },
    placeObjects: {
      _name: "place_objects",
      id: "id",
      resource: "resource",
      geometries: "geometries",
      length: "length",
      maxAltitude: "max_altitude",
      minAltitude: "min_altitude",
      openingHours: "opening_hours",
      address: "address",
      howToArrive: "how_to_arrive",
      snowConditions: "snow_conditions",
    },
  },
};
