const iso6391to6393 = {};

for (const [iso6393tag, iso6391tag] of Object.entries(
  require("iso-639-3/to-1.json")
)) {
  iso6391to6393[iso6391tag] = iso6393tag;
}

const eventCategoryToTopicId = {
  "schema:FoodEvent": "252200A028C8449D9A6205369A6D0D36", // 'Gastronomie/Typische Produkte'
  "schema:MusicEvent": "7E048074BA004EC58E29E330A9AA476B", // 'Musik/Tanz'
  "schema:Festival": "9C3449EE278C4D94AA5A7C286729DEA0", // 'Volksfeste/Festivals'
  "schema:SportsEvent": "162C0067811B477DA725D2F5F2D98398", // 'Sport'
  "schema:TheaterEvent": "6884FE362C88434B9F49725E3328112B", // 'Theater/Vorführungen'
  "schema:EducationEvent": "767F6F43FC394CE9A3C8A9725C6FF134", // 'Kurse/Bildung'
  "schema:BusinessEvent": "0D25868CC23242D6AC97AEB2973CB3D6", // 'Tagungen Vorträge'
  "schema:ChildrensEvent": "D98B49DF24C342D09A8161836435CF86", // 'Familie'
  "schema:VisualArtsEvent": "C72CE969B98947FABC99CBC7B033F28E", // 'Ausstellungen/Kunst'
  "odh:gastronomie-typische-produkte": "252200A028C8449D9A6205369A6D0D36", // 'Gastronomie/Typische Produkte'
  "odh:musik-tanz": "7E048074BA004EC58E29E330A9AA476B", // 'Musik/Tanz'
  "odh:volksfeste-festivals": "9C3449EE278C4D94AA5A7C286729DEA0", // 'Volksfeste/Festivals'
  "odh:sport": "162C0067811B477DA725D2F5F2D98398", // 'Sport'
  "odh:führungen-besichtigungen": "B5467FEFE5C74FA5AD32B83793A76165", // 'Führungen/Besichtigungen'
  "odh:theater-vorführungen": "6884FE362C88434B9F49725E3328112B", // 'Theater/Vorführungen'
  "odh:kurse-bildung": "767F6F43FC394CE9A3C8A9725C6FF134", // 'Kurse/Bildung'
  "odh:tagungen-vortrage": "0D25868CC23242D6AC97AEB2973CB3D6", // 'Tagungen Vorträge'
  "odh:familie": "D98B49DF24C342D09A8161836435CF86", // 'Familie'
  "odh:handwerk-brauchtum": "33BDC54BD39946F4852B3394B00610AE", // 'Handwerk/Brauchtum'
  "odh:messen-markte": "4C4961D9FC5B48EEB73067BEB9D4402A", // 'Messen/Märkte'
  "odh:wanderungen-ausflüge": "ACE8B613F2074A7BB59C0B1DD40A43CD", // 'Wanderungen/Ausflüge'
  "odh:ausstellungen-kunst": "C72CE969B98947FABC99CBC7B033F28E", // 'Ausstellungen/Kunst'
};

const eventCategoryToTopicBitmask = {
  "schema:BusinessEvent": 1,
  "schema:SportsEvent": 2,
  "schema:FoodEvent": 4,
  "schema:TheaterEvent": 32,
  "schema:EducationEvent": 64,
  "schema:MusicEvent": 128,
  "schema:Festival": 256,
  "schema:VisualArtsEvent": 2048,
  "schema:ChildrensEvent": 4096,
  "odh:tagungen-vortrage": 1,
  "odh:sport": 2,
  "odh:gastronomie-typische-produkte": 4,
  "odh:handwerk-brauchtum": 8,
  "odh:messen-markte": 16,
  "odh:theater-vorführungen": 32,
  "odh:kurse-bildung": 64,
  "odh:musik-tanz": 128,
  "odh:volksfeste-festivals": 256,
  "odh:wanderungen-ausflüge": 512,
  "odh:führungen-besichtigungen": 1024,
  "odh:ausstellungen-kunst": 2048,
  "odh:familie": 4096,
};

const eventTopicIdToAlpineBitsCategories = {
  "252200A028C8449D9A6205369A6D0D36": "schema:FoodEvent",
  "7E048074BA004EC58E29E330A9AA476B": "schema:MusicEvent",
  "9C3449EE278C4D94AA5A7C286729DEA0": "schema:Festival",
  "162C0067811B477DA725D2F5F2D98398": "schema:SportsEvent",
  "6884FE362C88434B9F49725E3328112B": "schema:TheaterEvent",
  "767F6F43FC394CE9A3C8A9725C6FF134": "schema:EducationEvent",
  "0D25868CC23242D6AC97AEB2973CB3D6": "schema:BusinessEvent",
  D98B49DF24C342D09A8161836435CF86: "schema:ChildrensEvent",
  C72CE969B98947FABC99CBC7B033F28E: "schema:VisualArtsEvent",
};

const eventTopicIdToODHCategories = {
  "252200A028C8449D9A6205369A6D0D36": "odh:gastronomie-typische-produkte",
  "7E048074BA004EC58E29E330A9AA476B": "odh:musik-tanz",
  "9C3449EE278C4D94AA5A7C286729DEA0": "odh:volksfeste-festivals",
  "162C0067811B477DA725D2F5F2D98398": "odh:sport",
  B5467FEFE5C74FA5AD32B83793A76165: "odh:führungen-besichtigungen",
  "6884FE362C88434B9F49725E3328112B": "odh:theater-vorführungen",
  "767F6F43FC394CE9A3C8A9725C6FF134": "odh:kurse-bildung",
  "0D25868CC23242D6AC97AEB2973CB3D6": "odh:tagungen-vortrage",
  D98B49DF24C342D09A8161836435CF86: "odh:familie",
  "33BDC54BD39946F4852B3394B00610AE": "odh:handwerk-brauchtum",
  "4C4961D9FC5B48EEB73067BEB9D4402A": "odh:messen-markte",
  ACE8B613F2074A7BB59C0B1DD40A43CD: "odh:wanderungen-ausflüge",
  C72CE969B98947FABC99CBC7B033F28E: "odh:ausstellungen-kunst",
};

const eventCategoryInOdhToSchemaOrg = {
  "odh:tagungen-vortrage": "schema:BusinessEvent",
  "odh:sport": "schema:SportsEvent",
  "odh:gastronomie-typische-produkte": "schema:FoodEvent",
  "odh:handwerk-brauchtum": null,
  "odh:messen-markte": null,
  "odh:theater-vorführungen": "schema:TheaterEvent",
  "odh:kurse-bildung": "schema:EducationEvent",
  "odh:musik-tanz": "schema:MusicEvent",
  "odh:volksfeste-festivals": "schema:Festival",
  "odh:wanderungen-ausflüge": null,
  "odh:führungen-besichtigungen": null,
  "odh:ausstellungen-kunst": "schema:VisualArtsEvent",
  "odh:familie": "schema:ChildrensEvent",
};

const eventCategoryInSchemaOrgToOdh = {
  "schema:BusinessEvent": "odh:tagungen-vortrage",
  "schema:SportsEvent": "odh:sport",
  "schema:FoodEvent": "odh:gastronomie-typische-produkte",
  "schema:TheaterEvent": "odh:theater-vorführungen",
  "schema:EducationEvent": "odh:kurse-bildung",
  "schema:MusicEvent": "odh:musik-tanz",
  "schema:Festival": "odh:volksfeste-festivals",
  "schema:VisualArtsEvent": "odh:ausstellungen-kunst",
  "schema:ChildrensEvent": "odh:familie",
};

const eventCategoryToNamespace = {
  "schema:BusinessEvent": "schema",
  "schema:SportsEvent": "schema",
  "schema:FoodEvent": "schema",
  "schema:TheaterEvent": "schema",
  "schema:EducationEvent": "schema",
  "schema:MusicEvent": "schema",
  "schema:Festival": "schema",
  "schema:VisualArtsEvent": "schema",
  "schema:ChildrensEvent": "schema",
  "odh:tagungen-vortrage": "odh",
  "odh:sport": "odh",
  "odh:gastronomie-typische-produkte": "odh",
  "odh:handwerk-brauchtum": "odh",
  "odh:messen-markte": "odh",
  "odh:theater-vorführungen": "odh",
  "odh:kurse-bildung": "odh",
  "odh:musik-tanz": "odh",
  "odh:volksfeste-festivals": "odh",
  "odh:wanderungen-ausflüge": "odh",
  "odh:führungen-besichtigungen": "odh",
  "odh:ausstellungen-kunst": "odh",
  "odh:familie": "odh",
};

const activityTypeIdToODHCategories = {
  Berg: "odh:berg",
  Radfahren: "odh:radfahren",
  Stadtrundgang: "odh:stadtrundgang",
  Pferdesport: "odh:pferdesport",
  Wandern: "odh:wandern",
  "Laufen und Fitness": "odh:laufen-und-fitness",
  Loipen: "odh:loipen",
  Piste: "odh:piste",
  Aufstiegsanlagen: "odh:aufstiegsanlagen",
  Alpinklettern: "odh:alpinklettern",
  Bergtouren: "odh:bergtouren",
  Hochtouren: "odh:hochtouren",
  Klettersteige: "odh:klettersteige",
  Schneeschuhtouren: "odh:schneeschuhtouren",
  Skitouren: "odh:skitouren",
  "Weitere Berge": "odh:weitere-berge",
  Eisklettern: "odh:eisklettern",
  Eistour: "odh:eistour",
  Downhills: "odh:downhills",
  "E-Bikes": "odh:e-bikes",
  Fernradwege: "odh:fernradwege",
  Mountainbikes: "odh:mountainbikes",
  "Mountainbike Transalps": "odh:mountainbike-transalps",
  Radtouren: "odh:radtouren",
  Rennräder: "odh:rennrader",
  "Weitere Radfahren": "odh:weitere-radfahren",
  Pumptrack: "odh:pumptrack",
  "Singletrail / Freeride": "odh:singletrail---freeride",
  Ortstouren: "odh:ortstouren",
  "Weitere Ortstouren": "odh:weitere-ortstouren",
  "Trail für Kutschenfahrten": "odh:trail-für-kutschenfahrten",
  "Trail für Reitpferde": "odh:trail-für-reitpferde",
  "Weitere Pferde": "odh:weitere-pferde",
  Barrierefrei: "odh:barrierefrei",
  Familienwanderungen: "odh:familienwanderungen",
  Fernwanderwege: "odh:fernwanderwege",
  Pilgerwege: "odh:pilgerwege",
  Schneeschuhwanderungen: "odh:schneeschuhwanderungen",
  Themenwanderungen: "odh:themenwanderungen",
  Winterwanderungen: "odh:winterwanderungen",
  "Kinderwagen tauglich": "odh:kinderwagen-tauglich",
  Waalweg: "odh:waalweg",
  "Weitere Wandern": "odh:weitere-wandern",
  Bergläufe: "odh:berglaufe",
  Fitnessparcours: "odh:fitnessparcours",
  "Innline Skating": "odh:innline-skating",
  Laufstrecken: "odh:laufstrecken",
  "Nordic Walkings": "odh:nordic-walkings",
  "Trail running": "odh:trail-running",
  "Weitere Laufen und Fitness": "odh:weitere-laufen-und-fitness",
  Klassisch: "odh:klassisch",
  Skating: "odh:skating",
  "Klassisch und Skating": "odh:klassisch-und-skating",
  Schienenrodelbahn: "odh:schienenrodelbahn",
  Eisbahnen: "odh:eisbahnen",
  Rodelbahnen: "odh:rodelbahnen",
  Schneebahnen: "odh:schneebahnen",
  "Weitere Rodeln": "odh:weitere-rodeln",
  "Ski alpin": "odh:ski-alpin",
  Snowpark: "odh:snowpark",
  Rundkurs: "odh:rundkurs",
  "Weitere Pisten": "odh:weitere-pisten",
  "nicht definiert": "odh:nicht-definiert",
  Seilbahn: "odh:seilbahn",
  Umlaufbahn: "odh:umlaufbahn",
  Kabinenbahn: "odh:kabinenbahn",
  "Unterirdische Bahn": "odh:unterirdische-bahn",
  Sessellift: "odh:sessellift",
  Skilift: "odh:skilift",
  Schrägaufzug: "odh:schragaufzug",
  "Standseilbahn/Zahnradbahn": "odh:standseilbahn-zahnradbahn",
  Telemix: "odh:telemix",
  Förderband: "odh:forderband",
  "2er Sessellift kuppelbar": "odh:2er-sessellift-kuppelbar",
  "3er Sessellift kuppelbar": "odh:3er-sessellift-kuppelbar",
  "4er Sessellift kuppelbar": "odh:4er-sessellift-kuppelbar",
  "6er Sessellift kuppelbar": "odh:6er-sessellift-kuppelbar",
  "8er Sessellift kuppelbar": "odh:8er-sessellift-kuppelbar",
  "Klein-Skilift": "odh:klein-skilift",
  Skibus: "odh:skibus",
  "1er Sessellift kuppelbar": "odh:1er-sessellift-kuppelbar",
  Zug: "odh:zug",
  "Weitere Aufstiegsanlagen": "odh:weitere-aufstiegsanlagen",
};

const activityTypeIdToAlpineBitsCategories = {
  Berg: null,
  Radfahren: null,
  Stadtrundgang: null,
  Pferdesport: null,
  Wandern: null,
  "Laufen und Fitness": null,
  Loipen: 'alpinebits:cross-country',
  Piste: null,
  Aufstiegsanlagen: null,
  Alpinklettern: null,
  Bergtouren: null,
  Hochtouren: null,
  Klettersteige: null,
  Schneeschuhtouren: null,
  Skitouren: null,
  "Weitere Berge": null,
  Eisklettern: null,
  Eistour: null,
  Downhills: null,
  "E-Bikes": null,
  Fernradwege: null,
  Mountainbikes: null,
  "Mountainbike Transalps": null,
  Radtouren: null,
  Rennräder: null,
  "Weitere Radfahren": null,
  Pumptrack: null,
  "Singletrail / Freeride": null,
  Ortstouren: null,
  "Weitere Ortstouren": null,
  "Trail für Kutschenfahrten": null,
  "Trail für Reitpferde": null,
  "Weitere Pferde": null,
  Barrierefrei: null,
  Familienwanderungen: null,
  Fernwanderwege: null,
  Pilgerwege: null,
  Schneeschuhwanderungen: null,
  Themenwanderungen: null,
  Winterwanderungen: null,
  "Kinderwagen tauglich": null,
  Waalweg: null,
  "Weitere Wandern": null,
  Bergläufe: null,
  Fitnessparcours: null,
  "Innline Skating": null,
  Laufstrecken: null,
  "Nordic Walkings": null,
  "Trail running": null,
  "Weitere Laufen und Fitness": null,
  Klassisch: null,
  Skating: null,
  "Klassisch und Skating": null,
  Schienenrodelbahn: null,
  Eisbahnen: null,
  Rodelbahnen: 'alpinebits:sledge-slope',
  Schneebahnen: null,
  "Weitere Rodeln": null,
  "Ski alpin": 'alpinebits:ski-slope',
  Snowpark: null,
  Rundkurs: 'alpinebits:ski-slope',
  "Weitere Pisten": null,
  "nicht definiert": null,
  Seilbahn: "alpinebits:cablecar",
  Umlaufbahn: "alpinebits:gondola",
  Kabinenbahn: "alpinebits:gondola",
  "Unterirdische Bahn": "alpinebits:funicular",
  Sessellift: "alpinebits:chairlift",
  Skilift: "alpinebits:skilift",
  Schrägaufzug: "alpinebits:funicular",
  "Standseilbahn/Zahnradbahn": "alpinebits:funicular",
  Telemix: "alpinebits:chairlift",
  Förderband: "alpinebits:magic-carpet",
  "2er Sessellift kuppelbar": null,
  "3er Sessellift kuppelbar": null,
  "4er Sessellift kuppelbar": null,
  "6er Sessellift kuppelbar": null,
  "8er Sessellift kuppelbar": null,
  "Klein-Skilift": null,
  Skibus: "alpinebits:skibus",
  "1er Sessellift kuppelbar": null,
  Zug: "alpinebits:train",
  "Weitere Aufstiegsanlagen": null,
};

const activitySmgTagToODHCategories = {
  'berg': 'odh:berg',
  'radfahren': 'odh:radfahren',
  'stadtrundgang': 'odh:stadtrundgang',
  'pferdesport': 'odh:pferdesport',
  'wandern': 'odh:wandern',
  'laufen und fitness': 'odh:laufen-und-fitness',
  'loipen': 'odh:loipen',
  'piste': 'odh:piste',
  'aufstiegsanlagen': 'odh:aufstiegsanlagen',
  'alpinklettern': 'odh:alpinklettern',
  'bergtouren': 'odh:bergtouren',
  'hochtouren': 'odh:hochtouren',
  'klettersteige': 'odh:klettersteige',
  'schneeschuhtouren': 'odh:schneeschuhtouren',
  'skitouren': 'odh:skitouren',
  'weitere berge': 'odh:weitere-berge',
  'eisklettern': 'odh:eisklettern',
  'eistour': 'odh:eistour',
  'downhills': 'odh:downhills',
  'e-bikes': 'odh:e-bikes',
  'fernradwege': 'odh:fernradwege',
  'mountainbikes': 'odh:mountainbikes',
  'mountainbike transalps': 'odh:mountainbike-transalps',
  'radtouren': 'odh:radtouren',
  'rennräder': 'odh:rennrader',
  'weitere radfahren': 'odh:weitere-radfahren',
  'pumptrack': 'odh:pumptrack',
  'singletrail / freeride': 'odh:singletrail---freeride',
  'ortstouren': 'odh:ortstouren',
  'weitere ortstouren': 'odh:weitere-ortstouren',
  'trail für kutschenfahrten': 'odh:trail-für-kutschenfahrten',
  'trail für reitpferde': 'odh:trail-für-reitpferde',
  'weitere pferde': 'odh:weitere-pferde',
  'barrierefrei': 'odh:barrierefrei',
  'familienwanderungen': 'odh:familienwanderungen',
  'fernwanderwege': 'odh:fernwanderwege',
  'pilgerwege': 'odh:pilgerwege',
  'schneeschuhwanderungen': 'odh:schneeschuhwanderungen',
  'themenwanderungen': 'odh:themenwanderungen',
  'winterwanderungen': 'odh:winterwanderungen',
  'kinderwagen tauglich': 'odh:kinderwagen-tauglich',
  'waalweg': 'odh:waalweg',
  'weitere wandern': 'odh:weitere-wandern',
  'bergläufe': 'odh:berglaufe',
  'fitnessparcours': 'odh:fitnessparcours',
  'innline skating': 'odh:innline-skating',
  'laufstrecken': 'odh:laufstrecken',
  'nordic walkings': 'odh:nordic-walkings',
  'trail running': 'odh:trail-running',
  'weitere laufen und fitness': 'odh:weitere-laufen-und-fitness',
  'klassisch': 'odh:klassisch',
  'skating': 'odh:skating',
  'klassisch und skating': 'odh:klassisch-und-skating',
  'schienenrodelbahn': 'odh:schienenrodelbahn',
  'eisbahnen': 'odh:eisbahnen',
  'rodelbahnen': 'odh:rodelbahnen',
  'schneebahnen': 'odh:schneebahnen',
  'weitere rodeln': 'odh:weitere-rodeln',
  'ski alpin': 'odh:ski-alpin',
  'snowpark': 'odh:snowpark',
  'rundkurs': 'odh:rundkurs',
  'weitere pisten': 'odh:weitere-pisten',
  'nicht definiert': 'odh:nicht-definiert',
  'seilbahn': 'odh:seilbahn',
  'umlaufbahn': 'odh:umlaufbahn',
  'kabinenbahn': 'odh:kabinenbahn',
  'unterirdische bahn': 'odh:unterirdische-bahn',
  'sessellift': 'odh:sessellift',
  'skilift': 'odh:skilift',
  'schrägaufzug': 'odh:schragaufzug',
  'standseilbahn/zahnradbahn': 'odh:standseilbahn-zahnradbahn',
  'telemix': 'odh:telemix',
  'förderband': 'odh:forderband',
  '2er sessellift kuppelbar': 'odh:2er-sessellift-kuppelbar',
  '3er sessellift kuppelbar': 'odh:3er-sessellift-kuppelbar',
  '4er sessellift kuppelbar': 'odh:4er-sessellift-kuppelbar',
  '6er sessellift kuppelbar': 'odh:6er-sessellift-kuppelbar',
  '8er sessellift kuppelbar': 'odh:8er-sessellift-kuppelbar',
  'klein-skilift': 'odh:klein-skilift',
  'skibus': 'odh:skibus',
  '1er sessellift kuppelbar': 'odh:1er-sessellift-kuppelbar',
  'zug': 'odh:zug',
  'weitere aufstiegsanlagen': 'odh:weitere-aufstiegsanlagen',
}

const activitySmgTagToAlpineBitsCategories = {
  'berg': null,
  'radfahren': null,
  'stadtrundgang': null,
  'pferdesport': null,
  'wandern': null,
  'laufen und fitness': null,
  'loipen': 'alpinebits:cross-country',
  'piste': null,
  'aufstiegsanlagen': null,
  'alpinklettern': null,
  'bergtouren': null,
  'hochtouren': null,
  'klettersteige': null,
  'schneeschuhtouren': null,
  'skitouren': null,
  'weitere berge': null,
  'eisklettern': null,
  'eistour': null,
  'downhills': null,
  'e-bikes': null,
  'fernradwege': null,
  'mountainbikes': null,
  'mountainbike transalps': null,
  'radtouren': null,
  'rennräder': null,
  'weitere radfahren': null,
  'pumptrack': null,
  'singletrail / freeride': null,
  'ortstouren': null,
  'weitere ortstouren': null,
  'trail für kutschenfahrten': null,
  'trail für reitpferde': null,
  'weitere pferde': null,
  'barrierefrei': null,
  'familienwanderungen': null,
  'fernwanderwege': null,
  'pilgerwege': null,
  'schneeschuhwanderungen': null,
  'themenwanderungen': null,
  'winterwanderungen': null,
  'kinderwagen tauglich': null,
  'waalweg': null,
  'weitere wandern': null,
  'bergläufe': null,
  'fitnessparcours': null,
  'innline skating': null,
  'laufstrecken': null,
  'nordic walkings': null,
  'trail running': null,
  'weitere laufen und fitness': null,
  'klassisch': null,
  'skating': null,
  'klassisch und skating': null,
  'schienenrodelbahn': null,
  'eisbahnen': null,
  'rodelbahnen': 'alpinebits:sledge-slope',
  'schneebahnen': null,
  'weitere rodeln': null,
  'ski alpin': 'alpinebits:ski-slope',
  'snowpark': null,
  'rundkurs': 'alpinebits:ski-slope',
  'weitere pisten': null,
  'nicht definiert': null,
  'seilbahn': 'alpinebits:cablecar',
  'umlaufbahn': 'alpinebits:gondola',
  'kabinenbahn': 'alpinebits:gondola',
  'unterirdische bahn': 'alpinebits:funicular',
  'sessellift': 'alpinebits:chairlift',
  'skilift': 'alpinebits:skilift',
  'schrägaufzug': 'alpinebits:funicular',
  'standseilbahn/zahnradbahn': 'alpinebits:funicular',
  'telemix': 'alpinebits:chairlift',
  'förderband': 'alpinebits:magic-carpet',
  '2er sessellift kuppelbar': null,
  '3er sessellift kuppelbar': null,
  '4er sessellift kuppelbar': null,
  '6er sessellift kuppelbar': null,
  '8er sessellift kuppelbar': null,
  'klein-skilift': null,
  'skibus': 'alpinebits:skibus',
  '1er sessellift kuppelbar': null,
  'zug': 'alpinebits:train',
  'weitere aufstiegsanlagen': null,
}

const skiAreaSmgTagToODHCategories = {
  skigebiete: 'odh:skigebiete',
  'dolomiti superski': 'odh:dolomiti-superski',
  familientip: 'odh:familientip',
  skiexperience2016: 'odh:skiexperience2016',
  'kleine skigebiete': 'odh:kleine-skigebiete',
  'skiregion tauferer ahrntal': 'odh:skiregion-tauferer-ahrntal',
  'ortler skiarena': 'odh:ortler-skiarena',
  'skiverbund eisacktal-wipptal': 'odh:skiverbund-eisacktal-wipptal'
}

module.exports = {
  eventTopicIdToAlpineBitsCategories,
  eventTopicIdToODHCategories,
  eventCategoryToTopicId,
  eventCategoryToTopicBitmask,
  eventCategoryInOdhToSchemaOrg,
  eventCategoryInSchemaOrgToOdh,
  eventCategoryToNamespace,
  activityTypeIdToAlpineBitsCategories,
  activityTypeIdToODHCategories,
  activitySmgTagToAlpineBitsCategories,
  activitySmgTagToODHCategories,
  skiAreaSmgTagToODHCategories,
  iso6391to6393,
};
