openapi: '3.0.2'
info:
  title: AlpineBits DestinationData Reference Server
  version: '1.0'
  description: This page presents the documentation of the AlpineBits
    DestinationData standard as implement by its reference server. 
servers:
  - url: http://localhost:8080
    description: Local Server
tags:
  - name: Base
    description: Requests to base endpoints
  - name: Events
    description: Requests related to `events` resources
  - name: Lifts
    description: Requests related to `lifts` resources
  - name: Mountain Areas
    description: Requests related to `mountainAreas` resources
  - name: Snowparks
    description: Requests related to `snowparks` resources
  - name: Trails
    description: Requests related to `trails` resources
paths:
  /:
    get:
      operationId: /
      description: Retrieves links to the  implemented versions of the
        AlpineBits DestinationData standard.
      tags:
        - Base
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              example:
                $ref: examples/base.yml#/base
  /1.0:
    get:
      operationId: /1.0
      description: Retrieves links to the resources available as base endpoints.
      tags:
        - Base
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              example:
                $ref: examples/base.yml#/baseVersion
  /1.0/events:
    $ref: paths/events.paths.yml#/events
  /1.0/events/{id}:
    $ref: paths/events.paths.yml#/eventsId
  /1.0/events/{id}/contributors:
    $ref: paths/events.paths.yml#/eventsIdContributors
  /1.0/events/{id}/multimediaDescriptions:
    $ref: paths/events.paths.yml#/eventsIdMultimediaDescriptions
  /1.0/events/{id}/organizers:
    $ref: paths/events.paths.yml#/eventsIdOrganizers
  /1.0/events/{id}/publisher:
    $ref: paths/events.paths.yml#/eventsIdPublisher
  /1.0/events/{id}/series:
    $ref: paths/events.paths.yml#/eventsIdSeries
  /1.0/events/{id}/sponsors:
    $ref: paths/events.paths.yml#/eventsIdSponsors
  /1.0/events/{id}/subEvents:
    $ref: paths/events.paths.yml#/eventsIdSubEvents
  /1.0/events/{id}/venues:
    $ref: paths/events.paths.yml#/eventsIdVenues
  /1.0/lifts:
    $ref: paths/lifts.paths.yml#/lifts
  /1.0/lifts/:id:
    $ref: paths/lifts.paths.yml#/liftsId
  /1.0/lifts/:id/connections:
    $ref: paths/lifts.paths.yml#/liftsIdConnections
  /1.0/lifts/:id/multimediaDescriptions:
    $ref: paths/lifts.paths.yml#/liftsIdMultimediaDescriptions
  /1.0/snowparks:
    $ref: paths/snowparks.paths.yml#/snowparks
  /1.0/snowparks/:id:
    $ref: paths/snowparks.paths.yml#/snowparksId
  /1.0/snowparks/:id/connections:
    $ref: paths/snowparks.paths.yml#/snowparksIdConnections
  /1.0/snowparks/:id/multimediaDescriptions:
    $ref: paths/snowparks.paths.yml#/snowparksIdMultimediaDescriptions
  /1.0/trails:
    $ref: paths/trails.paths.yml#/trails
  /1.0/trails/:id:
    $ref: paths/trails.paths.yml#/trailsId
  /1.0/trails/:id/connections:
    $ref: paths/trails.paths.yml#/trailsIdConnections
  /1.0/trails/:id/multimediaDescriptions:
    $ref: paths/trails.paths.yml#/trailsIdMultimediaDescriptions
  /1.0/mountainAreas:
    $ref: paths/mountainareas.paths.yml#/mountainAreas
  /1.0/mountainAreas/:id:
    $ref: paths/mountainareas.paths.yml#/mountainAreasId
  /1.0/mountainAreas/:id/areaOwner:
    $ref: paths/mountainareas.paths.yml#/mountainAreasIdAreaOwner
  /1.0/mountainAreas/:id/connections:
    $ref: paths/mountainareas.paths.yml#/mountainAreasIdConnections
  /1.0/mountainAreas/:id/lifts:
    $ref: paths/mountainareas.paths.yml#/mountainAreasIdLifts
  /1.0/mountainAreas/:id/multimediaDescriptions:
    $ref: paths/mountainareas.paths.yml#/mountainAreasIdMultimediaDescriptions
  /1.0/mountainAreas/:id/snowparks:
    $ref: paths/mountainareas.paths.yml#/mountainAreasIdSnowparks
  /1.0/mountainAreas/:id/subAreas:
    $ref: paths/mountainareas.paths.yml#/mountainAreasIdSubAreas
  /1.0/mountainAreas/:id/trails:
    $ref: paths/mountainareas.paths.yml#/mountainAreasIdTrails