name: CI

on: push


jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: app
      DOCKER_TAG: latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure
        run: |
          cp .env.example .env
          echo 'DOCKER_IMAGE=${DOCKER_IMAGE}' >> .env
          echo 'DOCKER_TAG=${DOCKER_TAG}' >> .env

      - name: Build
        run: docker-compose -f infrastructure/docker-compose.build.yml build
    
      - name: Shut down
        run: docker-compose -f infrastructure/docker-compose.build.yml down || true
